version: "3"

services:
  arex:
    image: arexadmin01/arex:$AREX_VERSION
    container_name: arex-front
    restart: always
    ports:
      - '8088:8080'
    volumes:
      - ./arex-logs/arex-front:/usr/src/app/logs
    environment:
      - SERVICE_REPORT_URL=http://arex-report-service:8080
      - SERVICE_SCHEDULE_URL=http://arex-schedule-service:8080
      - SERVICE_STORAGE_URL=http://arex-storage-service:8080
    depends_on:
      arex-report-service:
        condition: service_healthy

  arex-report-service:
    image: arexadmin01/arex-report:$AREX_VERSION
    container_name: arex-report
    restart: always
    ports:
      - '8090:8080'
    volumes:
      - ./arex-logs/arex-report:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Darex.report.mongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.redis.uri=redis://redis:6379/
        -Darex.storage.service.url=http://arex-storage-service:8080 
        -Darex.ui.url=http://arex:8080
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/vi/health"]
      interval: 1s
      timeout: 3s
      retries: 60
  arex-storage-service:
    image: arexadmin01/arex-storage-serive:$AREX_VERSION
    container_name: arex-storage
    restart: always
    ports:
      - '8093:8080'
    volumes:
      - ./arex-logs/arex-storage:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Darex.storage.mongo.host=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.storage.cache.url=redis://redis:6379/ 
        -Darex.report.service.api=http://arex-report-service:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/vi/health"]
      interval: 1s
      timeout: 3s
      retries: 60
    depends_on:
      arex-report-service:
        condition: service_healthy
  arex-schedule-service:
    image: arexadmin01/arex-replay-schedule:$AREX_VERSION
    container_name: arex-schedule
    restart: always
    ports:
      - '8092:8080'
    volumes:
      - ./arex-logs/arex-schedule:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Dmongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.schedule.cache.redis.host=redis://redis:6379
        -Darex.storage.service.api=http://arex-storage-service:8080 
        -Darex.report.service.api=http://arex-report-service:8080
    depends_on:
      arex-report-service:
        condition: service_healthy

  mongodb:
    image: mongo:5.0
    container_name: arex-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./arex-data/mongodb:/data/db
      - ./mongo-allone-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./arex-logs/mongodb:/var/log/mongodb
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=rootdb
      - MONGO_USERNAME=arex
      - MONGO_PASSWORD=iLoveArex
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  redis:
    image: redis:6.2.6
    container_name: arex-redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./arex-data/redis:/data
      - ./arex-logs/redis:/var/log/redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      timeout: 3s
      retries: 5
