version: "3"

services:
  gateway:
    container_name: gateway-nginx
    image: nginx
    volumes:
      - ./conf/nginx-gateway.conf:/etc/nginx/nginx.conf
      - ./arex-logs/nginx-gateway:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - arex
    networks:
      - internal-network 
      - public-network     
  arex:
    image: arexadmin01/arex:$AREX_VERSION
    container_name: arex
    restart: always
    expose:
      - "8080"
    volumes:
      - ./arex-logs/arex-front:/usr/src/app/logs
    environment:
      - SERVICE_REPORT_URL=http://arex-report-service:8080
      - SERVICE_SCHEDULE_URL=http://arex-schedule-service:8080
      - SERVICE_STORAGE_URL=http://arex-storage-service:8080
    depends_on:
      - arex-report-service
      - arex-schedule-service
      - arex-storage-service
    networks:
      - internal-network
  arex-report-service:
    image: arexadmin01/arex-report:$AREX_VERSION
    container_name: arex-report
    restart: always
    expose:
      - "8080"
    volumes:
      - ./arex-logs/arex-report:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Darex.report.mongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.redis.uri=redis://redis:6379/
        -Darex.storage.service.url=http://arex-storage-service:8080 
        -Darex.ui.url=http://arex:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - internal-network
  arex-storage-service1:
    image: arexadmin01/arex-storage-serive:$AREX_VERSION
    container_name: arex-storage1
    restart: always
    expose:
      - "8080"
    volumes:
      - ./arex-logs/arex-storage1:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Darex.storage.mongo.host=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.storage.cache.url=redis://redis:6379/ 
        -Darex.report.service.api=http://arex-report-service:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - internal-network
  arex-storage-service2:
    image: arexadmin01/arex-storage-serive:$AREX_VERSION
    container_name: arex-storage2
    restart: always
    expose:
      - "8080"
    volumes:
      - ./arex-logs/arex-storage2:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Darex.storage.mongo.host=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.storage.cache.url=redis://redis:6379/ 
        -Darex.report.service.api=http://arex-report-service:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - internal-network
  arex-storage-service:
    container_name: storage-nginx
    image: nginx
    volumes:
      - ./conf/nginx-storage.conf:/etc/nginx/nginx.conf
      - ./arex-logs/nginx-storage:/var/log/nginx
    expose:
      - "8080"
    depends_on:
      - arex-storage-service1
      - arex-storage-service2
    networks:
      - internal-network
  arex-schedule-service1:
    image: arexadmin01/arex-replay-schedule:$AREX_VERSION
    container_name: arex-schedule1
    restart: always
    expose:
      - "8080"
    volumes:
      - ./arex-logs/arex-schedule1:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Dmongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.schedule.cache.redis.host=redis://redis:6379
        -Darex.storage.service.api=http://arex-storage-service:8080 
        -Darex.report.service.api=http://arex-report-service:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - internal-network
  arex-schedule-service2:
    image: arexadmin01/arex-replay-schedule:$AREX_VERSION
    container_name: arex-schedule2
    restart: always
    expose:
      - "8080"
    volumes:
      - ./arex-logs/arex-schedule2:/usr/local/tomcat/logs
    environment:
      - JAVA_OPTS=-Dmongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db 
        -Darex.schedule.cache.redis.host=redis://redis:6379
        -Darex.storage.service.api=http://arex-storage-service:8080 
        -Darex.report.service.api=http://arex-report-service:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - internal-network
  arex-schedule-service:
    container_name: schedule-nginx
    image: nginx
    volumes:
      - ./conf/nginx-schedule.conf:/etc/nginx/nginx.conf
      - ./arex-logs/nginx-schedule:/var/log/nginx
    expose:
      - "8080"
    depends_on:
      - arex-schedule-service1
      - arex-schedule-service2
    networks:
      - internal-network
  mongodb:
    image: mongo:5.0
    container_name: arex-mongodb
    restart: always
    expose:
      - "27017"
    volumes:
      - ./arex-data/mongodb:/data/db
      - ./mongo-allone-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./arex-logs/mongodb:/var/log/mongodb
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=rootdb
      - MONGO_USERNAME=arex
      - MONGO_PASSWORD=iLoveArex
    networks:
      - internal-network
  redis:
    image: redis:6.2.6
    container_name: arex-redis
    restart: always
    command: --appendonly yes
    expose:
      - "6379"
    volumes:
      - ./arex-data/redis:/data
      - ./arex-logs/redis:/var/log/redis
    networks:
      - internal-network
networks:
  internal-network:
    internal: true
    driver_opts:
      com.docker.network.gateway: 10.5.153.151
  public-network:
