version: "3"

services:
  arex-ui:
    image: arexadmin01/arex-ui:0.2.6
    container_name: arex-front
    restart: always
    ports:
      - '8088:8080'
    volumes:
      - ./arex-logs/arex-front:/usr/src/app/logs
    environment:
      - SERVICE_REPORT_URL=http://arex-report-service:8080
      - SERVICE_NODE_URL=http://arex-node:3000
      - SERVICE_SCHEDULE_URL=http://arex-schedule-service:8080
      - SERVICE_STORAGE_URL=http://arex-storage-service:8080
      - OTEL_TRACE_HOST=10.5.153.151
      - OTEL_TRACE_PORT=4318
      - OTEL_TRACE_SERVICE=AREX-UI
    depends_on:
      - arex-report-service
      - arex-schedule-service
      - arex-storage-service
      - arex-node
  arex-node:
    image: arexadmin01/arex-node:0.2.6
    container_name: arex-node
    restart: always
    ports:
      - '10001:3000'
    environment:
      - OTEL_TRACE_HOST=10.5.153.151
      - OTEL_TRACE_PORT=4318
      - OTEL_TRACE_SERVICE=AREX-SANDBOX
    volumes:
      - ./arex-logs/arex-node:/usr/src/app/logs
  arex-report-service:
    image: arexadmin01/arex-report:0.2.6
    container_name: arex-report
    restart: always
    ports:
      - '8090:8080'
    volumes:
      - ./arex-logs/arex-report:/usr/local/tomcat/logs
      - ./agent/opentelemetry-javaagent.jar:/shared/opentelemetry-javaagent.jar
    environment:
      - JAVA_OPTS=-Dmongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db -Darex.storage.service.url=http://arex-storage-service:8080 -Darex.ui.url=http://arex:8080
      - JAVA_TOOL_OPTIONS="-javaagent:/shared/opentelemetry-javaagent.jar"
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.5.153.151:4318/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINTT=http://10.5.153.151:4318
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=SERVICE_REPORT
      - OTEL_RESOURCE_ATTRIBUTES="application=AREX"
    depends_on:
      - mongodb  
  arex-storage-service:
    image: arexadmin01/arex-storage-serive:0.2.6
    container_name: arex-storage
    restart: always
    ports:
      - '8093:8080'
    volumes:
      - ./arex-logs/arex-storage:/usr/local/tomcat/logs
      - ./agent/opentelemetry-javaagent.jar:/shared/opentelemetry-javaagent.jar
    environment:
      - "JAVA_OPTS=-Darex.storage.mongo.host=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db -Darex.report.service.api=http://arex-report-service:8080"
      - JAVA_TOOL_OPTIONS="-javaagent:/shared/opentelemetry-javaagent.jar"
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.5.153.151/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINTT=http://10.5.153.151:4318
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=SERVICE_STORAGE
      - OTEL_RESOURCE_ATTRIBUTES="application=AREX"
    depends_on:
      - mongodb
      - redis
  arex-schedule-service:
    image: arexadmin01/arex-replay-schedule:0.2.6
    container_name: arex-schedule
    restart: always
    ports:
      - '8092:8080'
    volumes:
      - ./arex-logs/arex-schedule:/usr/local/tomcat/logs
      - ./agent/opentelemetry-javaagent.jar:/shared/opentelemetry-javaagent.jar
    environment:
      - JAVA_OPTS=-Dmongo.uri=mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db -Darex.storage.service.api=http://arex-storage-service:8080 -Darex.report.service.api=http://arex-report-service:8080
      - JAVA_TOOL_OPTIONS="-javaagent:/shared/opentelemetry-javaagent.jar"
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.5.153.151:4318/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINTT=http://10.5.153.151:4318
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=SERVICE_SCHEDULE
      - OTEL_RESOURCE_ATTRIBUTES="application=AREX"
    depends_on:
      - mongodb
      - redis
  arex-community-test:
    image: arexadmin01/arex-community-test:0.0.1
    container_name: arex-commnity-test
    privileged: true
    user: "root"
    restart: always
    ports:
      - '18080:8080'
    volumes:
      - ./arex-community/logs/community:/usr/local/tomcat/logs
      - ./agent/opentelemetry-javaagent.jar:/shared/opentelemetry-javaagent.jar
    environment:
      - JAVA_TOOL_OPTIONS='-javaagent:/shared/opentelemetry-javaagent.jar -javaagent:/usr/local/tomcat/arex-agent-0.1.0.jar' -Darex.service.name=community-otel -Darex.storage.service.host=arex-storage-service:8093 -Darex.enable.debug=true  -Dspring.datasource.url=jdbc:mysql://cmysql:3306/community?useUnicode=true&characterEncoding=utf-8 -Dspring.datasource.username=arex_admin -Dspring.datasource.password=arex_admin_password -Dspring.redis.host=redis -Dspring.redis.port=6379
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.5.153.151:4318/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINTT=http://10.5.153.151:4318
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=AREX_COMMUNITY_TEST
      - OTEL_RESOURCE_ATTRIBUTES="application=AREX"
    depends_on:
      - cmysql
      - redis
      - arex-storage-service
  cmysql:
    image: mysql:8.0.29
    container_name: community-mysql
    privileged: true
    user: "root"
    restart: always
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=arex_admin
      - MYSQL_PASSWORD=arex_admin_password
      - MYSQL_DATABASE=community
    volumes:
      - ./community_init/:/docker-entrypoint-initdb.d/
      - ./conf.d:/etc/mysql/conf.d:ro
      - ./arex-community/mysql:/var/lib/mysql
      - ./arex-community/logs/mysql:/var/log/mysql.log
  mongodb:
    image: mongo:5.0
    container_name: arex-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./arex-data/mongodb:/data/db
      - ./mongo-allone-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./arex-logs/mongodb:/var/log/mongodb
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=rootdb
      - MONGO_USERNAME=arex
      - MONGO_PASSWORD=iLoveArex
  redis:
    image: redis:6.2.6
    container_name: arex-redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./arex-data/redis:/data
      - ./arex-logs/redis:/var/log/redis
