apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arex-mongodb-pvc
spec:
  storageClassName: arex-local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arex-redis-pvc
spec:
  storageClassName: arex-local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
