{{- if .Values.config.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "arex.name" . }}-{{ .Values.config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.config.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "arex.config.fullname" . }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector: 
    matchLabels:
      app: {{ template "arex.name" . }}-{{ .Values.config.name }}
  template:
    metadata:
    {{- if .Values.config.podAnnotations }}
      annotations:
{{ toYaml .Values.config.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "arex.name" . }}-{{ .Values.config.name }}
        component: "{{ .Values.config.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "arex.name" . }}-{{ .Values.config.name }}
          image: "{{ .Values.registerPre }}{{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}"
          imagePullPolicy: "{{ .Values.config.image.pullPolicy }}"
          args:
          {{- range $key, $value := .Values.config.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          env:          
            - name: JAVA_OPTS
              value: -Dmongo.uri=mongodb://arex:iLoveArex@{{ template "arex.mongodb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mongodb.service.servicePort }}/arex_storage_db
          ports:
            - containerPort: {{ .Values.config.service.servicePort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.config.service.servicePort }}
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
{{ toYaml .Values.config.resources | indent 12 }}
    {{- if .Values.config.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.config.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.config.tolerations }}
      tolerations:
{{ toYaml .Values.config.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.config.affinity }}
      affinity:
{{ toYaml .Values.config.affinity | indent 8 }}
    {{- end }}
{{- end }}

