{{- if .Values.config.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.config.service.annotations }}
  annotations:
{{ toYaml .Values.config.service.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "arex.name" . }}-{{ .Values.config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.config.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.config.service.labels }}
{{ toYaml .Values.config.service.labels | indent 4}}
{{- end }}
  name: {{ template "arex.config.fullname" . }}
spec:
{{- if .Values.config.service.clusterIP }}
  clusterIP: {{ .Values.config.service.clusterIP }}
{{- end }}
{{- if .Values.config.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.config.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.config.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.config.service.loadBalancerIP }}
{{- end }}
{{- if .Values.config.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.config.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.config.service.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.config.service.servicePort }}
  selector:
    app: {{ template "arex.name" . }}-{{ .Values.config.name }}
    component: "{{ .Values.config.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.config.service.type }}"
{{- end }}

