{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arex-pv-redis-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.redis.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: arex-redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
  storageClassName: local-storage
{{- end}}