apiVersion: v1
kind: ConfigMap
metadata:
  name: arex-configmap
data:
  myvalue: "just-demo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arex-mongodb-init
data:
  mongo-allone-init.js: |
    db = db.getSiblingDB("arex_storage_db");
    db.createUser({
      user: "arex",
      pwd: "iLoveArex",
      roles: [{ role: "readWrite", db: "arex_storage_db" }],
    });
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
data:
  mongodb.conf: |
    logpath=/data/mongodb/mongodb.log
    pidfilepath=/data/mongodb/master.pid
    directoryperdb=true
    logappend=true
    bind_ip=0.0.0.0
    port=27017
